<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('languages')->insert([

            /**
             * ISO 639-1 Language Codes
             * Useful in Locale analysis
             *
             * References :
             * 1. http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
             * 2. http://blog.xoundboy.com/?p=235
             */

            ['code' => 'en', 'name' => 'English'],
            ['code' => 'aa', 'name' => 'Afar'],
            ['code' => 'ab', 'name' => 'Abkhazian'],
            ['code' => 'af', 'name' => 'Afrikaans'],
            ['code' => 'am', 'name' => 'Amharic'],
            ['code' => 'ar', 'name' => 'Arabic'],
            ['code' => 'as', 'name' => 'Assamese'],
            ['code' => 'ay', 'name' => 'Aymara'],
            ['code' => 'az', 'name' => 'Azerbaijani'],
            ['code' => 'ba', 'name' => 'Bashkir'],
            ['code' => 'be', 'name' => 'Byelorussian'],
            ['code' => 'bg', 'name' => 'Bulgarian'],
            ['code' => 'bh', 'name' => 'Bihari'],
            ['code' => 'bi', 'name' => 'Bislama'],
            ['code' => 'bn', 'name' => 'Bengali/Bangla'],
            ['code' => 'bo', 'name' => 'Tibetan'],
            ['code' => 'br', 'name' => 'Breton'],
            ['code' => 'ca', 'name' => 'Catalan'],
            ['code' => 'co', 'name' => 'Corsican'],
            ['code' => 'cs', 'name' => 'Czech'],
            ['code' => 'cy', 'name' => 'Welsh'],
            ['code' => 'da', 'name' => 'Danish'],
            ['code' => 'de', 'name' => 'German'],
            ['code' => 'dz', 'name' => 'Bhutani'],
            ['code' => 'el', 'name' => 'Greek'],
            ['code' => 'eo', 'name' => 'Esperanto'],
            ['code' => 'es', 'name' => 'Spanish'],
            ['code' => 'et', 'name' => 'Estonian'],
            ['code' => 'eu', 'name' => 'Basque'],
            ['code' => 'fa', 'name' => 'Persian'],
            ['code' => 'fi', 'name' => 'Finnish'],
            ['code' => 'fj', 'name' => 'Fiji'],
            ['code' => 'fo', 'name' => 'Faeroese'],
            ['code' => 'fr', 'name' => 'French'],
            ['code' => 'fy', 'name' => 'Frisian'],
            ['code' => 'ga', 'name' => 'Irish'],
            ['code' => 'gd', 'name' => 'Scots/Gaelic'],
            ['code' => 'gl', 'name' => 'Galician'],
            ['code' => 'gn', 'name' => 'Guarani'],
            ['code' => 'gu', 'name' => 'Gujarati'],
            ['code' => 'ha', 'name' => 'Hausa'],
            ['code' => 'hi', 'name' => 'Hindi'],
            ['code' => 'hr', 'name' => 'Croatian'],
            ['code' => 'hu', 'name' => 'Hungarian'],
            ['code' => 'hy', 'name' => 'Armenian'],
            ['code' => 'ia', 'name' => 'Interlingua'],
            ['code' => 'ie', 'name' => 'Interlingue'],
            ['code' => 'ik', 'name' => 'Inupiak'],
            ['code' => 'in', 'name' => 'Indonesian'],
            ['code' => 'is', 'name' => 'Icelandic'],
            ['code' => 'it', 'name' => 'Italian'],
            ['code' => 'iw', 'name' => 'Hebrew'],
            ['code' => 'ja', 'name' => 'Japanese'],
            ['code' => 'ji', 'name' => 'Yiddish'],
            ['code' => 'jw', 'name' => 'Javanese'],
            ['code' => 'ka', 'name' => 'Georgian'],
            ['code' => 'kk', 'name' => 'Kazakh'],
            ['code' => 'kl', 'name' => 'Greenlandic'],
            ['code' => 'km', 'name' => 'Cambodian'],
            ['code' => 'kn', 'name' => 'Kannada'],
            ['code' => 'ko', 'name' => 'Korean'],
            ['code' => 'ks', 'name' => 'Kashmiri'],
            ['code' => 'ku', 'name' => 'Kurdish'],
            ['code' => 'ky', 'name' => 'Kirghiz'],
            ['code' => 'la', 'name' => 'Latin'],
            ['code' => 'ln', 'name' => 'Lingala'],
            ['code' => 'lo', 'name' => 'Laothian'],
            ['code' => 'lt', 'name' => 'Lithuanian'],
            ['code' => 'lv', 'name' => 'Latvian/Lettish'],
            ['code' => 'mg', 'name' => 'Malagasy'],
            ['code' => 'mi', 'name' => 'Maori'],
            ['code' => 'mk', 'name' => 'Macedonian'],
            ['code' => 'ml', 'name' => 'Malayalam'],
            ['code' => 'mn', 'name' => 'Mongolian'],
            ['code' => 'mo', 'name' => 'Moldavian'],
            ['code' => 'mr', 'name' => 'Marathi'],
            ['code' => 'ms', 'name' => 'Malay'],
            ['code' => 'mt', 'name' => 'Maltese'],
            ['code' => 'my', 'name' => 'Burmese'],
            ['code' => 'na', 'name' => 'Nauru'],
            ['code' => 'ne', 'name' => 'Nepali'],
            ['code' => 'nl', 'name' => 'Dutch'],
            ['code' => 'no', 'name' => 'Norwegian'],
            ['code' => 'oc', 'name' => 'Occitan'],
            ['code' => 'om', 'name' => '(Afan)/Oromoor/Oriya'],
            ['code' => 'pa', 'name' => 'Punjabi'],
            ['code' => 'pl', 'name' => 'Polish'],
            ['code' => 'ps', 'name' => 'Pashto/Pushto'],
            ['code' => 'pt', 'name' => 'Portuguese'],
            ['code' => 'qu', 'name' => 'Quechua'],
            ['code' => 'rm', 'name' => 'Rhaeto-Romance'],
            ['code' => 'rn', 'name' => 'Kirundi'],
            ['code' => 'ro', 'name' => 'Romanian'],
            ['code' => 'ru', 'name' => 'Russian'],
            ['code' => 'rw', 'name' => 'Kinyarwanda'],
            ['code' => 'sa', 'name' => 'Sanskrit'],
            ['code' => 'sd', 'name' => 'Sindhi'],
            ['code' => 'sg', 'name' => 'Sangro'],
            ['code' => 'sh', 'name' => 'Serbo-Croatian'],
            ['code' => 'si', 'name' => 'Singhalese'],
            ['code' => 'sk', 'name' => 'Slovak'],
            ['code' => 'sl', 'name' => 'Slovenian'],
            ['code' => 'sm', 'name' => 'Samoan'],
            ['code' => 'sn', 'name' => 'Shona'],
            ['code' => 'so', 'name' => 'Somali'],
            ['code' => 'sq', 'name' => 'Albanian'],
            ['code' => 'sr', 'name' => 'Serbian'],
            ['code' => 'ss', 'name' => 'Siswati'],
            ['code' => 'st', 'name' => 'Sesotho'],
            ['code' => 'su', 'name' => 'Sundanese'],
            ['code' => 'sv', 'name' => 'Swedish'],
            ['code' => 'sw', 'name' => 'Swahili'],
            ['code' => 'ta', 'name' => 'Tamil'],
            ['code' => 'te', 'name' => 'Tegulu'],
            ['code' => 'tg', 'name' => 'Tajik'],
            ['code' => 'th', 'name' => 'Thai'],
            ['code' => 'ti', 'name' => 'Tigrinya'],
            ['code' => 'tk', 'name' => 'Turkmen'],
            ['code' => 'tl', 'name' => 'Tagalog'],
            ['code' => 'tn', 'name' => 'Setswana'],
            ['code' => 'to', 'name' => 'Tonga'],
            ['code' => 'tr', 'name' => 'Turkish'],
            ['code' => 'ts', 'name' => 'Tsonga'],
            ['code' => 'tt', 'name' => 'Tatar'],
            ['code' => 'tw', 'name' => 'Twi'],
            ['code' => 'uk', 'name' => 'Ukrainian'],
            ['code' => 'ur', 'name' => 'Urdu'],
            ['code' => 'uz', 'name' => 'Uzbek'],
            ['code' => 'vi', 'name' => 'Vietnamese'],
            ['code' => 'vo', 'name' => 'Volapuk'],
            ['code' => 'wo', 'name' => 'Wolof'],
            ['code' => 'xh', 'name' => 'Xhosa'],
            ['code' => 'yo', 'name' => 'Yoruba'],
            ['code' => 'zh', 'name' => 'Chinese'],
            ['code' => 'zu', 'name' => 'Zulu'],
        ]);
    }
}
