<?php

namespace App\Services;

use App\Enums\NewsPostType;
use App\Support\ActPressReleaseData;
use App\Support\PressReleaseData;
use OpenAI\Laravel\Facades\OpenAI;

/**
 * PressReleaseAgent
 * A service for using the power of AI to generate "press releases" for the Contest.
 * Generated by ChatGPT, refined by me.
 *
 * @package App\Services
 */
class PressReleaseAgent
{
    /* Example usage:

    $agent = app(PressReleaseAgent::class);

    $result = $agent->spotlight(
        new NewEntrySpotlightData(
            title: 'Magenta Men',
            description: 'A funk-based duo inspired by Prince and Morris Day',
            highlights: [
                'Dual male leads',
                'Retro-funk aesthetic',
                'High-energy performances',
            ],
            tone: 'playful',
            voice: 'flamboyant, rhythmic, confident'
        )
    );
    return response()->json($press);
    */

    protected string $model = 'gpt-4.1-mini';

    public function __construct()
    {
        $this->model = config('contest.ai.model', 'gpt-4.1-mini');
    }

    protected function systemPrompt(): string
    {
        return <<<PROMPT
You are a professional press officer for Song Contest by CATAWOL Records.

Your role is to write compelling, polished press releases based on structured input.

General rules:
- Always include a strong, attention-grabbing headline
- Open with a clear summary (who, what, why it matters)
- Match tone to the press release type
- Use vivid but controlled language (avoid fluff)
- Include quotes when provided or generate one if missing
- End with a clear call to action

Press release types and styles:

Contest Announcement:
- Big, exciting, promotional
- Focus on scale and participation

Results Announcement:
- Dramatic and celebratory
- Emphasise winners and impact

Artist Feature:
- Personal and narrative
- Explore background and artistic identity

Event Promotion:
- Urgent and time-sensitive
- Focus on attendance

Return JSON with:
- title
- content (Markdown format with level 2 headings).
PROMPT;
    }

    protected function run(PressReleaseData $data): array
    {
        $payload = $data->toArray();

        $response = OpenAI::chat()->create([
            'model'           => $this->model,
            'temperature'     => $this->temperature($payload['type']),
            'response_format' => ['type' => 'json_object'],
            'messages'        => [
                [
                    'role'    => 'system',
                    'content' => $this->systemPrompt(),
                ],
                [
                    'role'    => 'user',
                    'content' => "Generate a press release using this data:\n\n"
                        . json_encode($payload, JSON_PRETTY_PRINT),
                ],
            ],
        ]);

        return json_decode(
            $response->choices[0]->message->content,
            true
        );
    }

    /**
     * Returns the "temperature" to use for the press release response.
     * Temperature controls how "creative" the output is: 0 being restrained and 1 being risky.
     *
     * @param NewsPostType|null $type
     * @return float
     */
    protected function temperature(?NewsPostType $type): float
    {
        $type = $type ?? NewsPostType::GENERAL;
        return config("ai.temperature.$type->value", 0.7);
    }

    // Different types of press releases...

    /**
     * Generate a press release about a specific Act.
     *
     * @param ActPressReleaseData $data
     * @return array
     */
    public function actFeature(ActPressReleaseData $data): array
    {
        return $this->run($data);
    }

}
