<?php

namespace App\Services;

use App\Enums\NewsPostType;
use App\Exceptions\PressReleaseException;
use App\Support\PressRelease\ActPressReleaseData;
use App\Support\PressRelease\ContestPressReleaseData;
use App\Support\PressRelease\GeneralPressReleaseData;
use App\Support\PressRelease\ResultsPressReleaseData;
use App\Support\PressRelease\RoundPressReleaseData;
use App\Support\PressRelease\StagePressReleaseData;
use App\Support\PressReleaseData;
use App\Support\PressReleaseResponse;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Log;
use OpenAI\Laravel\Facades\OpenAI;
use OpenAI\Responses\Chat\CreateResponse;
use Throwable;

/**
 * PressReleaseAgent
 * A service for using the power of AI to generate "press releases" for the Contest.
 * Generated by ChatGPT, refined by me.
 *
 * @package App\Services
 */
class PressReleaseAgent
{
    /* Example usage:

    $agent = app(PressReleaseAgent::class);

    $result = $agent->spotlight(
        new ActPressReleaseData(
            title: 'Magenta Men',
            description: 'A funk-based duo inspired by Prince and Morris Day',
            highlights: ['Dual male leads', 'Retro-funk aesthetic'],
        )
    );

    // Clean access
    echo $result->title;
    echo $result->content;

    // Or convert if needed
    return response()->json($result->toArray());
    */

    protected string $model;

    public function __construct()
    {
        $this->model = config('contest.ai.model');
    }

    /**
     * @param PressReleaseData $data
     * @param array            $history a list of previous News posts to use for reference.
     * @return PressReleaseResponse
     * @throws PressReleaseException
     */
    protected function run(PressReleaseData $data, array $history = []): PressReleaseResponse
    {
        $payload = $data->toArray();

        $max_attempts = config('contest.ai.retry.attempts', 3);
        $backoff      = config('contest.ai.retry.backoff_ms', 150);

        $last_error = null;

        for ($attempt = 1; $attempt <= $max_attempts; $attempt++)
        {
            try
            {
                $response = $this->callOpenAI($payload, $attempt, $history);

                $decoded = json_decode(
                    $response->choices[0]->message->content,
                    true
                );

                if (!is_array($decoded))
                {
                    throw new PressReleaseException('Invalid JSON response');
                }

                logger()->info(
                    "OpenAI token usage:\n" .
                    "  prompt:     {$response->usage->promptTokens}\n" .
                    "  completion: {$response->usage->completionTokens}\n" .
                    "  total:      {$response->usage->totalTokens}"
                );

                return $this->mapToResult($decoded);
            }
            catch (\OpenAI\Exceptions\ErrorException $e) {
                abort(500, 'PressReleaseAgent failed: ' . $e->getMessage());
            }
            catch (Throwable $e)
            {
                $last_error = $e;
                Log::warning('PressReleaseAgent attempt failed', [
                    'attempt' => $attempt,
                    'error'   => $e->getMessage(),
                ]);
                // Small delay before retry
                usleep($backoff * 1000);
            }
        }

        throw new PressReleaseException(
            "PressReleaseAgent failed after $max_attempts retries.",
            previous: $last_error
        );
    }

    protected function callOpenAI(array $payload, int $attempt, array $history): CreateResponse
    {
        // Lower the temperature on retries (for a more deterministic response).
        $baseTemp    = $this->temperature(NewsPostType::from($payload['type']));
        $temperature = max(0.2, $baseTemp - (($attempt - 1) * 0.2));

        return OpenAI::chat()->create([
            'model'           => config('contest.ai.model'),
            'temperature'     => $temperature,
            'response_format' => ['type' => 'json_object'],
            'messages'        => [
                [
                    'role'    => 'system',
                    'content' => Lang::get('press-release.prompt.system'),
                ],
                [
                    'role'    => 'user',
                    'content' => $this->buildPrompt($payload, $attempt, $history),
                ],
            ],
        ]);
    }

    protected function formatHistory(array $history): string
    {
        if (empty($history))
        {
            return 'No prior press releases.';
        }

        return collect($history)
            ->take(5)
            ->map(function ($item, $index)
            {
                return sprintf(
                    "Example %d:\nHeadline: %s\nPublished on %s\nBody: %s",
                    $index + 1,
                    $item['title'],
                    $item['published'],
                    $item['content']
                );
            })
            ->implode("\n\n");
    }

    protected function buildPrompt(array $payload, int $attempt, array $history): string
    {
        return Lang::get($attempt === 1 ? 'press-release.prompt.begin' : 'press-release.prompt.retry', [
            'history' => $this->formatHistory($history),
            'data'    => $this->prettyJson($payload)
        ]);
    }

    protected function prettyJson(array $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT);
    }

    /**
     * Returns the "temperature" to use for the press release response.
     * Temperature controls how "creative" the output is: 0 being restrained and 1 being risky.
     *
     * @param NewsPostType|null $type
     * @return float
     */
    protected function temperature(?NewsPostType $type): float
    {
        $type = $type ?? NewsPostType::GENERAL;
        return config("ai.temperature.$type->value", 0.7);
    }

    /**
     * Maps the data from the AI response to the properties of PressReleaseResponse.
     *
     * @param array $data
     * @return PressReleaseResponse
     */
    protected function mapToResult(array $data): PressReleaseResponse
    {
        // Fallbacks (in case AI slightly deviates)
        $normalized = [
            'title'   => $data['title'] ?? '',
            'content' => $data['content'] ?? ''
        ];

        return PressReleaseResponse::fromArray($normalized);
    }

    /**
     * Generate a press release about a specific Act.
     *
     * @param ActPressReleaseData $data
     * @param array               $history
     * @return PressReleaseResponse
     * @throws PressReleaseException
     */
    public function actPressRelease(ActPressReleaseData $data, array $history = []): PressReleaseResponse
    {
        return $this->run($data, $history);
    }

    /**
     * Generate a general/custom press release.
     *
     * @param GeneralPressReleaseData $data
     * @param array                   $history
     * @return PressReleaseResponse
     * @throws PressReleaseException
     */
    public function generalPressRelease(GeneralPressReleaseData $data, array $history = []): PressReleaseResponse
    {
        return $this->run($data, $history);
    }

    /**
     * Generate a press release about a specific Stage.
     *
     * @param StagePressReleaseData $data
     * @param array                 $history
     * @return PressReleaseResponse
     * @throws PressReleaseException
     */
    public function stagePressRelease(StagePressReleaseData $data, array $history = []): PressReleaseResponse
    {
        return $this->run($data, $history);
    }

    /**
     * Generate a press release about the current results of the Contest.
     *
     * @param ResultsPressReleaseData $data
     * @return PressReleaseResponse
     * @throws PressReleaseException
     */
    public function resultsPressRelease(ResultsPressReleaseData $data): PressReleaseResponse
    {
        return $this->run($data);
    }

    /**
     * Generate a press release about a specific Round of the Contest.
     *
     * @param RoundPressReleaseData $data
     * @param array                 $history
     * @return PressReleaseResponse
     * @throws PressReleaseException
     */
    public function roundPressRelease(RoundPressReleaseData $data, array $history = []): PressReleaseResponse
    {
        return $this->run($data, $history);
    }

    /**
     * Generate a press release about the current state of the Contest.
     *
     * @param string $description
     * @param array  $history
     * @return PressReleaseResponse
     * @throws PressReleaseException
     */
    public function contestPressRelease(string $description, array $history = []): PressReleaseResponse
    {
        return $this->run(new ContestPressReleaseData($description), $history);
    }

}
