<?php

namespace App\Services;

use App\Enums\NewsPostType;
use App\Support\ActPressReleaseData;
use App\Support\PressReleaseData;
use App\Support\PressReleaseResponse;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Log;
use OpenAI\Laravel\Facades\OpenAI;
use OpenAI\Responses\Chat\CreateResponse;
use RuntimeException;
use Throwable;

/**
 * PressReleaseAgent
 * A service for using the power of AI to generate "press releases" for the Contest.
 * Generated by ChatGPT, refined by me.
 *
 * @package App\Services
 */
class PressReleaseAgent
{
    /* Example usage:

    $agent = app(PressReleaseAgent::class);

    $result = $agent->spotlight(
        new ActPressReleaseData(
            title: 'Magenta Men',
            description: 'A funk-based duo inspired by Prince and Morris Day',
            highlights: ['Dual male leads', 'Retro-funk aesthetic'],
        )
    );

    // Clean access
    echo $result->headline;
    echo $result->body;

    // Or convert if needed
    return response()->json($result->toArray());
    */

    protected string $model = 'gpt-4.1-mini';

    public function __construct()
    {
        $this->model = config('contest.ai.model', 'gpt-4.1-mini');
    }

    protected function run(PressReleaseData $data): PressReleaseResponse
    {
        $payload = $data->toArray();

        $maxAttempts = config('ai.retry.attempts', 3);
        $backoff     = config('ai.retry.backoff_ms', 150);

        $lastError = null;

        for ($attempt = 1; $attempt <= $maxAttempts; $attempt++)
        {
            try
            {
                $response = $this->callOpenAI($payload, $attempt);

                $decoded = json_decode(
                    $response->choices[0]->message->content,
                    true
                );

                if (!is_array($decoded))
                {
                    throw new RuntimeException('Invalid JSON response');
                }

                return $this->mapToResult($decoded);

            }
            catch (Throwable $e)
            {
                $lastError = $e;
                Log::warning('PressReleaseAgent attempt failed', [
                    'attempt' => $attempt,
                    'error'   => $e->getMessage(),
                ]);
                // Small delay before retry
                usleep($backoff * 1000);
            }
        }

        throw new RuntimeException(
            "PressReleaseAgent failed after $maxAttempts retries.",
            previous: $lastError
        );
    }

    protected function callOpenAI(array $payload, int $attempt): CreateResponse
    {
        // Lower temperature on retries (more deterministic).
        $baseTemp    = $this->temperature($payload['type']);
        $temperature = max(0.2, $baseTemp - (($attempt - 1) * 0.2));

        return OpenAI::chat()->create([
            'model'           => config('ai.model'),
            'temperature'     => $temperature,
            'response_format' => ['type' => 'json_object'],
            'messages'        => [
                [
                    'role'    => 'system',
                    'content' => Lang::get('press-release.prompt'),
                ],
                [
                    'role'    => 'user',
                    'content' => $this->buildPrompt($payload, $attempt),
                ],
            ],
        ]);
    }

    protected function buildPrompt(array $payload, int $attempt): string
    {
        if ($attempt === 1)
        {
            return "Generate a press release using this data:\n\n"
                . json_encode($payload, JSON_PRETTY_PRINT);
        }

        return <<<PROMPT
Your previous response was invalid or did not match the required JSON format.

You MUST:
- Return valid JSON only
- Include exactly these fields: title, content
- Ensure all fields are strings
- Do not include any extra text outside JSON

Try again using this data:

{$this->prettyJson($payload)}
PROMPT;
    }

    protected function prettyJson(array $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT);
    }

    /**
     * Returns the "temperature" to use for the press release response.
     * Temperature controls how "creative" the output is: 0 being restrained and 1 being risky.
     *
     * @param NewsPostType|null $type
     * @return float
     */
    protected function temperature(?NewsPostType $type): float
    {
        $type = $type ?? NewsPostType::GENERAL;
        return config("ai.temperature.$type->value", 0.7);
    }

    /**
     * Maps the data from the AI response to the properties of PressReleaseResponse.
     *
     * @param array $data
     * @return PressReleaseResponse
     */
    protected function mapToResult(array $data): PressReleaseResponse
    {
        // Fallbacks (in case AI slightly deviates)
        $normalized = [
            'title'   => $data['title'] ?? '',
            'content' => $data['content'] ?? ''
        ];

        return PressReleaseResponse::fromArray($normalized);
    }

    /**
     * Generate a press release about a specific Act.
     *
     * @param ActPressReleaseData $data
     * @return PressReleaseResponse
     */
    public function actFeature(ActPressReleaseData $data): PressReleaseResponse
    {
        return $this->run($data);
    }

}
