<?php

// Originally generated by ChatGPT, modified by me.

namespace App\Http\Controllers\API;

use App\Http\Requests\GoldenBuzzerRequest;
use App\Mail\GoldenBuzzerConfirmation;
use App\Models\GoldenBuzzer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

/**
 * BuzzerController
 * This endpoint does the same thing as the Donation endpoint, but we want to specifically record
 * Golden Buzzer donations, which will require additional information.
 *
 * @package App\Http\Controllers\API
 */
class BuzzerController extends DonationController
{

    protected function getRequestData(): Request
    {
        return GoldenBuzzerRequest::createFrom(request());
    }

    protected function recordDonation(array $transaction_details): void
    {
        $donation = GoldenBuzzer::create([
            ...$transaction_details,
            'round_id' => $this->request_data['round_id'],
            'song_id'  => $this->request_data['song_id']
        ]);

        if ($transaction_details['email'])
        {
            Mail::to($transaction_details['email'])->send(new GoldenBuzzerConfirmation($donation));
        }
    }

}
