<?php

// Originally generated by ChatGPT, modified by me.

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\DonationRequest;
use App\Models\Donation;
use App\Services\PayPalService;
use Illuminate\Http\JsonResponse;

class DonationController extends Controller
{

    /**
     * Capture the payment for a PayPal order.
     *
     * @param DonationRequest $request
     * @param PayPalService   $paypal
     * @return JsonResponse
     */
    public function store(DonationRequest $request, PayPalService $paypal): JsonResponse
    {
        $data = $request->validated();

        // At this point the order should have COMPLETED status, as capturing happens in the front end.
        $transaction = $paypal->verifyOrder($data['transaction_id']);

        if (!$transaction || $transaction['status'] !== 'COMPLETED')
        {
            return response()->json(['error' => 'Transaction is invalid or incomplete.'], 400);
        }

        // Success!
        Donation::create([
            'transaction_id' => $transaction['id'],
            'name'           => $transaction['purchase_units'][0]['payments']['captures'][0]['name'],
            'amount'         => $transaction['purchase_units'][0]['payments']['captures'][0]['amount']['value'],
            'currency'       => $transaction['purchase_units'][0]['payments']['captures'][0]['currency'],
            'message'        => $data['message'],
        ]);

        // To support refunds later, store capture_id as well — available in:
        // transaction.purchase_units[0].payments.captures[0].id

        // TODO send an email.

        return response()->json(['status' => "Verified!"], 201);
    }
}
