import { usePage } from '@inertiajs/react';
import { PayPalButtons, PayPalButtonsComponentProps, PayPalScriptProvider, ReactPayPalScriptOptions } from '@paypal/react-paypal-js';
import axios from 'axios';
import React from 'react';

// Generated by ChatGPT, modified by me.
// The ChatGPT solution manually added the PayPal JS SDK script to the page and rendered buttons,
// while I opted to use React components instead.
// https://developer.paypal.com/sdk/js/reference/

// TODO no need for the shipping address, if possible.
// TODO configurable amount.
// TODO configurable details (purpose of donation, etc.).
// TODO callbacks for success/error etc.

interface DonationButtonProps {
    currency: string;
}

interface OrderData {
    id: string;
    details?: {
        issue: string;
        description: string;
    }[];
    debug_id?: string;
}

export const PaypalButton: React.FC<DonationButtonProps> = ({ currency = 'USD' }) => {
    // see AppServiceProvider.php.
    const { paypalClientId } = usePage().props;

    const scriptOptions: ReactPayPalScriptOptions = {
        clientId: paypalClientId as string,
        disableFunding: ['credit'],
        enableFunding: ['card', 'venmo'],
    };

    const buttonStyle: PayPalButtonsComponentProps['style'] = {
        shape: 'rect',
        label: 'paypal',
        layout: 'horizontal',
        tagline: false,
    };

    /**
     * Set up a PayPal order (opens the popup window).
     * If successful, the order information is returned.
     */
    const createOrderHandler: PayPalButtonsComponentProps['createOrder'] = async (data, actions) => {
        return actions.order.create({
            intent: 'CAPTURE',
            purchase_units: [
                {
                    amount: {
                        currency_code: currency,
                        value: '10.00', // You can make this dynamic
                    },
                },
            ],
        });
    };

    /**
     * Handle the approval for the PayPal payment.
     */
    const approveHandler: PayPalButtonsComponentProps['onApprove'] = async (data, actions) => {
        // The transaction has been approved, but the payment has to be captured before funds can be recieved.
        // For some reason, I had no luck trying to do the capture on the backend.
        const transaction = await actions.order?.capture();

        if (transaction) {
            return axios
                .post('/donation', {
                    transaction_id: transaction.id,
                })
                .then((response) => {
                    // Show success message to buyer
                    console.log(response.data.status);
                })
                .catch((response) => {
                    console.log('error:', response.data.error);
                });
            }
            else {
                throw 'No order details!';
            }
        };

    return (
        <PayPalScriptProvider options={scriptOptions}>
            <PayPalButtons style={buttonStyle} createOrder={createOrderHandler} onApprove={approveHandler} />
        </PayPalScriptProvider>
    );
};
